package net.teachingprogramming.exam2.p2;

import java.util.ArrayList;

public class ResultData {
    static ArrayList<Result> getResultList() {
        ArrayList<Result> resultList = new ArrayList<>();
        resultList.add(new Result("4月2日", "愛媛MP", "香川OG", 7, 2));
        resultList.add(new Result("4月2日", "ソフトバンク", "高知FD", 1, 0));
        resultList.add(new Result("4月8日", "愛媛MP", "高知FD", 7, 3));
        resultList.add(new Result("4月9日", "ソフトバンク", "香川OG", 1, 7));
        resultList.add(new Result("4月9日", "巨人", "愛媛MP", 0, 1));
        resultList.add(new Result("4月10日", "ソフトバンク", "香川OG", 3, 0));
        resultList.add(new Result("4月10日", "巨人", "愛媛MP", 4, 5));
        resultList.add(new Result("4月13日", "高知FD", "愛媛MP", 2, 2));
        resultList.add(new Result("4月14日", "香川OG", "高知FD", 2, 5));
        resultList.add(new Result("4月15日", "徳島IS", "香川OG", 3, 5));
        resultList.add(new Result("4月16日", "愛媛MP", "徳島IS", 2, 4));
        resultList.add(new Result("4月17日", "香川OG", "徳島IS", 0, 6));
        resultList.add(new Result("4月20日", "愛媛MP", "徳島IS", 3, 1));
        resultList.add(new Result("4月21日", "巨人", "高知FD", 0, 0));
        resultList.add(new Result("4月22日", "香川OG", "愛媛MP", 1, 3));
        resultList.add(new Result("4月22日", "巨人", "高知FD", 2, 0));
        resultList.add(new Result("4月23日", "徳島IS", "高知FD", 1, 0));
        resultList.add(new Result("4月23日", "巨人", "香川OG", 5, 4));
        resultList.add(new Result("4月24日", "徳島IS", "香川OG", 3, 2));
        resultList.add(new Result("4月24日", "愛媛MP", "高知FD", 0, 1));
        resultList.add(new Result("4月26日", "愛媛MP", "ソフトバンク", 3, 5));
        resultList.add(new Result("4月28日", "高知FD", "徳島IS", 4, 2));
        resultList.add(new Result("4月28日", "愛媛MP", "ソフトバンク", 7, 0));
        resultList.add(new Result("4月29日", "高知FD", "香川OG", 6, 0));
        resultList.add(new Result("4月29日", "愛媛MP", "徳島IS", 2, 6));
        resultList.add(new Result("4月30日", "愛媛MP", "香川OG", 5, 1));
        resultList.add(new Result("4月30日", "高知FD", "徳島IS", 0, 7));
        resultList.add(new Result("5月1日", "愛媛MP", "高知FD", 6, 1));
        resultList.add(new Result("5月1日", "香川OG", "徳島IS", 2, 4));
        resultList.add(new Result("5月2日", "愛媛MP", "香川OG", 1, 2));
        resultList.add(new Result("5月3日", "香川OG", "徳島IS", 12, 5));
        resultList.add(new Result("5月4日", "徳島IS", "香川OG", 9, 3));
        resultList.add(new Result("5月4日", "ソフトバンク", "愛媛MP", 1, 3));
        resultList.add(new Result("5月4日", "巨人", "高知FD", 2, 7));
        resultList.add(new Result("5月5日", "香川OG", "高知FD", 8, 7));
        resultList.add(new Result("5月5日", "ソフトバンク", "愛媛MP", 1, 2));
        resultList.add(new Result("5月5日", "巨人", "徳島IS", 2, 1));
        resultList.add(new Result("5月5日", "香川OG", "高知FD", 1, 4));
        resultList.add(new Result("5月6日", "巨人", "香川OG", 4, 2));
        resultList.add(new Result("5月7日", "ソフトバンク", "徳島IS", 1, 3));
        resultList.add(new Result("5月7日", "巨人", "香川OG", 4, 8));
        resultList.add(new Result("5月8日", "香川OG", "愛媛MP", 1, 8));
        resultList.add(new Result("5月8日", "ソフトバンク", "徳島IS", 4, 13));
        resultList.add(new Result("5月9日", "高知FD", "ソフトバンク", 0, 3));
        resultList.add(new Result("5月10日", "徳島IS", "愛媛MP", 0, 4));
        resultList.add(new Result("5月11日", "徳島IS", "愛媛MP", 8, 2));
        resultList.add(new Result("5月11日", "高知FD", "ソフトバンク", 3, 3));
        resultList.add(new Result("5月12日", "高知FD", "愛媛MP", 7, 1));
        resultList.add(new Result("5月12日", "徳島IS", "香川OG", 3, 1));
        resultList.add(new Result("5月13日", "徳島IS", "高知FD", 4, 7));
        resultList.add(new Result("5月14日", "徳島IS", "高知FD", 5, 5));
        resultList.add(new Result("5月14日", "香川OG", "ソフトバンク", 6, 2));
        resultList.add(new Result("5月15日", "愛媛MP", "徳島IS", 5, 9));
        resultList.add(new Result("5月15日", "香川OG", "ソフトバンク", 8, 3));
        resultList.add(new Result("5月17日", "徳島IS", "愛媛MP", 0, 2));
        resultList.add(new Result("5月18日", "高知FD", "香川OG", 1, 2));
        resultList.add(new Result("5月18日", "巨人", "徳島IS", 0, 1));
        resultList.add(new Result("5月19日", "巨人", "徳島IS", 1, 2));
        resultList.add(new Result("5月20日", "巨人", "愛媛MP", 4, 4));
        resultList.add(new Result("5月21日", "香川OG", "愛媛MP", 2, 3));
        resultList.add(new Result("5月21日", "徳島IS", "ソフトバンク", 5, 0));
        resultList.add(new Result("5月22日", "高知FD", "愛媛MP", 4, 2));
        resultList.add(new Result("5月22日", "徳島IS", "ソフトバンク", 0, 2));
        resultList.add(new Result("5月23日", "愛媛MP", "高知FD", 9, 4));
        resultList.add(new Result("5月24日", "高知FD", "香川OG", 3, 4));
        resultList.add(new Result("5月25日", "徳島IS", "愛媛MP", 7, 8));
        resultList.add(new Result("5月25日", "高知FD", "香川OG", 0, 9));
        resultList.add(new Result("5月27日", "香川OG", "愛媛MP", 3, 9));
        resultList.add(new Result("5月27日", "高知FD", "徳島IS", 2, 8));
        resultList.add(new Result("5月27日", "高知FD", "徳島IS", 5, 9));
        resultList.add(new Result("5月28日", "高知FD", "愛媛MP", 3, 8));
        resultList.add(new Result("5月28日", "香川OG", "徳島IS", 3, 1));
        resultList.add(new Result("5月29日", "愛媛MP", "香川OG", 1, 6));
        resultList.add(new Result("5月30日", "ソフトバンク", "高知FD", 2, 1));
        resultList.add(new Result("5月31日", "香川OG", "高知FD", 4, 5));
        resultList.add(new Result("5月31日", "徳島IS", "高知FD", 2, 1));
        return resultList;
    }
}
